theme: minima
plugins:
- jekyll-remote-theme

header_pages:
  - about.md

title: Homogenous Ensemble Learning in Highly Imbalanced Data
description: Predictive Model on Recipe Data

minima:
  skin: classic