title: Robust Homogenous Ensemble Learning for Recommendation
description: More Reliable Predictive Model on Recipe Data

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

github:
  another_url: https://github.com/KevinBian107/ensemble_imbalance_data