remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: [Homogenous Ensemble Learning in Highly Unbalanced Data]

github:
  zip_url: https://github.com/KevinBian107/ensemble_unbalance_data