remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: Homogenous Ensemble Learning in Highly Unbalanced Data
description: Predictive Recipe Rating Model
author: Kaiwen Bian & Bella Wang