title: Homogenous Ensemble Learning in Highly Unbalanced Data
author: Kaiwen Bian & Bella Wang
  name: GitHub User
  email: kbian@ucsd.edu

description: >
This project demonstrate how we may draw insights from a highly unbalanced data set using ensemble learning

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag