remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: [Homogenous Ensemble Learning in Highly Unbalanced Data]
description: [This project demonstrate how we may draw insights from a highly unbalanced data set using ensemble learning]