theme: minima
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme

minima:
  skin: auto

title: Homogenous Ensemble Learning in Highly Imbalanced Data
description: Predictive Model on Recipe Data