title: Homogenous Ensemble Learning in Highly Imbalanced Data
description: Predictive Model on Recipe Data

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

github:
  zip_url:
  another_url: